

CREATE TABLE Memory(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Question NVARCHAR(MAX),
    Answer NVARCHAR(MAX),
    SerialNumber  NVARCHAR(300),
    CreatedAt DATETIME2 DEFAULT SYSDATETIME()
)


DROP TABLE Memory